In [5]:
import sys
sys.path.append('/home/yluo/Documents/rivet-python')
from pyrivet import rivet
#Equivalent to the 'points2.txt' sample data file in the RIVET distribution
# Function-VRips Filtration
points = rivet.PointCloud(
    points = [
        (0.3, 1.5, 2.1), # will appear at 1
        (4.2, 3.8, 4.9), # will appear at 3.2
        (5.6, 2.3, 6),   # will appear at 2
        (2.9, 5.1, 3.3), # will appear at 4
        (3.3, 2.0, 2.5), # will appear at 2.5
        (4.1, 1.1, 2.3), # will appear at 2.4
        (1.1, 1.3, 1.7), # will appear at 2
    ],
    second_param_name='appearance',
    appearance=[1, 3.2, 2, 4, 2.5, 2.4, 2],
    max_dist=3.1 # pyrivet will calculate max_dist if you leave it out
)

# 7 points, 3 dimensions
# 6 function values => 6 grades in one dimension for function values
# 7 points => 7+1=8 grades in another dimension for distance

# Now let's take the Betti information
betti = rivet.betti(points)

In [6]:
print("Betti information:")
print("rank")
print(betti.graded_rank)

print("xi_0")
print(betti.xi_0)

print("xi_1")
print(betti.xi_1)

print("xi_2")
print(betti.xi_2)

print("x(row) grades")
print(betti.dimensions.x_grades)
print("y(column) grades")
print(betti.dimensions.y_grades)

Betti information:
rank
[[1. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 3. 4. 5.]
 [1. 2. 3. 3. 3. 4.]
 [1. 2. 3. 3. 3. 3.]
 [1. 2. 3. 2. 2. 2.]
 [1. 2. 2. 2. 2. 2.]
 [1. 2. 2. 2. 2. 2.]]
xi_0
[(0, 0, 1), (1, 0, 2), (2, 0, 1), (3, 0, 1), (4, 0, 1), (5, 0, 1)]
xi_1
[(1, 1, 1), (2, 6, 1), (3, 2, 1), (3, 5, 1), (4, 3, 1), (5, 4, 1)]
xi_2
[(3, 6, 1)]
x(row) grades
[Fraction(1, 1), Fraction(2, 1), Fraction(12, 5), Fraction(5, 2), Fraction(16, 5), Fraction(4, 1)]
y(column) grades
[Fraction(0, 1), Fraction(9165151, 10000000), Fraction(244131, 200000), Fraction(2328089, 1000000), Fraction(2437211, 1000000), Fraction(1221679, 500000), Fraction(3065941, 1000000), Fraction(766893, 250000)]


In [7]:
import pandas as pd
# round the x_grades and y_grades to 2 decimal places and store them in a list
x_grades = [round(grade.numerator/grade.denominator, 2) for grade in betti.dimensions.x_grades]
y_grades = [round(grade.numerator/grade.denominator, 4) for grade in betti.dimensions.y_grades]

# transform the betti into a dataframe with rows and columbs labels as the grades 
betti_df = pd.DataFrame(betti.graded_rank.T, index=x_grades, columns=y_grades)
# add column names to the dataframe
betti_df.columns.name = 'distance'
betti_df.index.name = 'function value'
# convert the value to int
betti_df = betti_df.astype(int)
betti_df


distance,0.0000,0.9165,1.2207,2.3281,2.4372,2.4434,3.0659,3.0676
function value,,,,,,,,
1.0,1,1,1,1,1,1,1,1
2.0,3,2,2,2,2,2,2,2
2.4,4,3,3,3,3,3,2,2
2.5,5,4,3,3,3,2,2,2
3.2,6,5,4,3,3,2,2,2
4.0,7,6,5,4,3,2,2,2


In [13]:
from graph_mph import compute_absolute_MPH0_multi_critical_filtration, compute_grid_H0
from scipy.spatial import distance
import numpy as np
D1 = np.array([
    [0,0],
    [3,4],
    [-5,12]
])

# compute the absolute MPH0 with multiple critical values
n = D1.shape[0]
pd_mat = distance.squareform(distance.pdist(D1)) 
betti0s, betti1s, betti2s = compute_absolute_MPH0_multi_critical_filtration(pd_mat)
print("betti0s")
print(betti0s)
print("betti1s")
print(betti1s)
print("betti2s")
print(betti2s)


betti0s
[[ 0.         0.       ]
 [ 5.        -1.       ]
 [13.        -2.       ]
 [ 0.         0.       ]
 [ 5.        -1.       ]
 [11.3137085 -2.       ]
 [ 0.         0.       ]
 [11.3137085 -1.       ]
 [13.        -2.       ]]
betti1s
[[ 5.         0.       ]
 [13.        -1.       ]
 [ 5.         0.       ]
 [11.3137085 -1.       ]
 [11.3137085  0.       ]
 [13.        -1.       ]
 [ 5.        -1.       ]
 [11.3137085 -1.       ]
 [13.        -2.       ]
 [13.        -2.       ]]
betti2s
[[13. -1.]
 [13. -1.]]
