In [1]:
import sys
sys.path.append('/root/Codes/graph-mph0/build')
import abmph
import numpy as np

In [2]:
# Define node features and edge features as 2D arrays
node_features = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=float)
edge_features = np.array([[5.0, 6.0], [7.0, 8.0]], dtype=float)

# Define node labels and edges
node_labels = np.array([0, 1], dtype=int)
edges_input = np.array([[0, 1],[1, 0]], dtype=int)

# Create the Graph object
graph = abmph.Graph(node_labels, node_features, edges_input, edge_features)


Check input of Graph constructor:
node_labels:
 0 1
node_features:
 (1, 2) (3, 4)
edges_input:
 (0,1) (1,0)
edge_features:
 (5, 6) (7, 8)


In [ ]:
abmph.compute_MPH0_DTree(graph)

In [3]:
graph.print_adjacency()

Print Adjacency
v = 1: Edge(0, 1, id = 1) Edge(0, 1, id = 2) 
v = 0: Edge(0, 1, id = 1) Edge(0, 1, id = 2) 


In [4]:
graph.print_filtration_value()

Graph filtration values:
Vertices:
f(0) = (1, 2)
f(1) = (3, 4)
Edges:
e = Edge(0, 1, id = 2), f(e)= (7, 8)
e = Edge(0, 1, id = 1), f(e)= (5, 6)


In [ ]:
abmph.compute_MPH0_Dengrogram(graph)

Done with Algo 2

([(1.0, 2.0), (3.0, 4.0)],
 [(5.0, 6.0)],
 [],
 [(7.0, 8.0)],
 [(1, 1, -1), (2, 1, 1)])


Converting vector of size: 2
Item: (1, 2)
Item: (3, 4)
Converting vector of size: 1
Item: (5, 6)
Converting vector of size: 0
Converting vector of size: 1
Item: (7, 8)


In [6]:
graph.print_adjacency()
graph.print_filtration_value()

Print Adjacency
v = 1: Edge(0, 1, id = 1) Edge(0, 1, id = 2) 
v = 0: Edge(0, 1, id = 1) Edge(0, 1, id = 2) 
Graph filtration values:
Vertices:
f(0) = (1, 2)
f(1) = (3, 4)
Edges:
e = Edge(0, 1, id = 2), f(e)= (7, 8)
e = Edge(0, 1, id = 1), f(e)= (5, 6)


In [ ]:
abmph.compute_MPH0_DTree(graph)


into the fucntion compute_MPH0_DTree


([(1.0, 2.0), (3.0, 4.0)],
 [(5.0, 6.0)],
 [],
 [(7.0, 8.0)],
 [(1, 1, -1), (2, 1, 1)])

Done with Algo 2
Converting vector of size: 2
Item: (1, 2)
Item: (3, 4)
Converting vector of size: 1
Item: (5, 6)
Converting vector of size: 0
Converting vector of size: 1
Item: (7, 8)


## dgl graph to mph graph

In [2]:
import dgl
import torch
import torch.nn as nn
import torch.nn.functional as F
import dgl.data
dataset = dgl.data.TUDataset(name = 'Cuneiform', raw_dir='../data')
print('Number of categories:', dataset.num_classes)

/root/miniconda3/envs/dl/lib/python3.10/site-packages/torchdata/datapipes/__init__.py:18: UserWarning: 
################################################################################
WARNING!
The 'datapipes', 'dataloader2' modules are deprecated and will be removed in a
future torchdata release! Please see https://github.com/pytorch/data/issues/1196
to learn more and leave feedback.
################################################################################

  deprecation_warning()
/root/miniconda3/envs/dl/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Number of categories: 30


In [3]:
len(dataset)

267

In [4]:
g, label = dataset[0]
g

Graph(num_nodes=36, num_edges=180,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'node_attr': Scheme(shape=(3,), dtype=torch.float64), 'node_labels': Scheme(shape=(2,), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'node_labels': Scheme(shape=(2,), dtype=torch.float64), 'edge_labels': Scheme(shape=(1,), dtype=torch.int64)})

In [5]:
g.edges(form='all',  order='srcdst')

(tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  2,  2,  2,  3,
          3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  6,  6,
          6,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,
         10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13,
         13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
         16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20,
         20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24, 24, 24, 24,
         24, 24, 24, 24, 24, 25, 25, 25, 26, 26, 26, 27, 27, 27, 28, 28, 28, 28,
         28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 30, 30, 30, 31, 31, 31, 32, 32,
         32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 34, 34, 34, 35, 35, 35]),
 tensor([ 1,  2,  3,  4,  8, 12, 16, 20, 24, 28, 32,  0,  2,  3,  0,  1,  3,  0,
          1,  2,  0,  5,  6,  7,  8, 12, 16, 20, 24, 28, 32,  4,  6,  7,  4,  5,
          7,  4,  5,  6,  

In [6]:
g.edata['_ID']

tensor([  0,   2,   4, 108, 109, 110, 111, 112, 113, 114, 115,   1,   6,   8,
          3,   7,  10,   5,   9,  11,  12,  14,  16, 116, 117, 118, 119, 120,
        121, 122, 123,  13,  18,  20,  15,  19,  22,  17,  21,  23,  24,  26,
         28, 124, 125, 126, 127, 128, 129, 130, 131,  25,  30,  32,  27,  31,
         34,  29,  33,  35,  36,  38,  40, 132, 133, 134, 135, 136, 137, 138,
        139,  37,  42,  44,  39,  43,  46,  41,  45,  47,  48,  50,  52, 140,
        141, 142, 143, 144, 145, 146, 147,  49,  54,  56,  51,  55,  58,  53,
         57,  59,  60,  62,  64, 148, 149, 150, 151, 152, 153, 154, 155,  61,
         66,  68,  63,  67,  70,  65,  69,  71,  72,  74,  76, 156, 157, 158,
        159, 160, 161, 162, 163,  73,  78,  80,  75,  79,  82,  77,  81,  83,
         84,  86,  88, 164, 165, 166, 167, 168, 169, 170, 171,  85,  90,  92,
         87,  91,  94,  89,  93,  95,  96,  98, 100, 172, 173, 174, 175, 176,
        177, 178, 179,  97, 102, 104,  99, 103, 106, 101, 105, 1

In [7]:
e_feature = g.edata['node_labels']
e_feature

tensor([[ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [-5.1201, -1.4581],
        [-3.5998, -5.6597],
        [-3.7676, -3.9864],
        [-3.6892, -2.3657],
        [-3.4658, -0.2373],
        [-7.1075, -1.5701],
        [-6.8954, -3.8223],
        [-5.7408, -4.0384],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 5.1201,  1.4581],
        [ 1.5202, -4.2017],
        [ 1.3525, -2.5283],
        [ 1.4309, -0.9077],
        [ 1.6543,  1.2208],
        [-1.9875, -0.1120],
        [-1.7753, -2.3642],
        [-0.6207, -2.5803],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0

In [8]:
abmph.Graph?

Docstring:      <no docstring>
Init docstring:
__init__(*args, **kwargs)
Overloaded function.

1. __init__(self: abmph._abmph.Graph, arg0: int) -> None

2. __init__(self: abmph._abmph.Graph, node_labels: list[int], node_features: list[R2], edges_input: list[tuple[int, int]], edge_features: list[R2]) -> None
File:           ~/Codes/graph-mph0/build/abmph/_abmph.cpython-310-x86_64-linux-gnu.so
Type:           pybind11_type
Subclasses:     